export const EMAIL_CHANGED = 'email_changed';
export const PASSWORD_CHANGED = 'password_changed';
export const _types = {
   LOGIN_USER: 'login_user',
   LOGIN_SUCCESS: 'login_success',
   LOGIN_FAIL: 'login_fail',
   BUTTON_PRESS: 'button_press',
   GET_SALONS: 'get_salons',
   GET_SALONS_SUCCESS: 'get_salon_success',
   GET_SALONS_FAIL: 'get_Salons_fail',
   SALON_CREATE: 'salon_create',
   GET_AREA_DETAILS: 'get_area_details',
   SELECTED_AREA: 'selected_Area',
   USER_LOCATION: 'user_location',
   NEAR_SALONS_GOOGLE_DATA: 'google_data',
   GOOGLE_FETCH_ERROR: 'google_data_fetch_error',
   SALON_CLASSES: 'salon_classes',
   SALON_DATA_ADDED: 'salon_data_added',
   OP_CITIES: 'operating_cities',
   OP_AREA_BY_CITY_ID: 'operatingAreaByCityId',
   GET_BUSINESS_CATEGORY: 'businessCategory',
   GOT_SALON_AREA: 'got_Salon_area',
   GOT_SALON_CATEGORY: 'got_Salon_category',
   GOT_SALON_CITY: 'got_salon_city',
   GOT_SALON_CLASS: 'got_salon_class',
   NEW_SALON_SAVE: 'new_salon_added',
   SALON_ADD_FAIL: 'salonAddFail',
   SALON_ADDED_SUCCESS: 'salonAddedSuccess',
   SALON_ADD_BUTTON_PRESSED: 'salonButtonPress',
   SHOW_PASSWORD: 'show_password_True',
   SALON_TYPE_SELECTED: 'salon_Type_selected',
   ADD_SALON_LOCATION: 'add_salon_location',
   ADD_SALON_LOCATION_FAIL: 'add_salon_location_fail',
   AC_CHANGED: 'AcChanged',
    TV_CHANGED: 'TvChanged',
    MUSIC_CHANGED: 'MusicChanged',
    WIFI_CHANGED:'WifiChanged',
}